// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sftuxbssbhdipuzotdbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmdHV4YnNzYmhkaXB1em90ZGJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTg0OTcsImV4cCI6MjA2MzQzNDQ5N30.K0Uz9Jr-IQ4OLd7zLybEju8HPZNbeKLwafSCa4cIFWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);